version: '3'

services:
  web:
    build: .
    container_name: flight-finder
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - HOST=0.0.0.0
      - DOCKER_BUILDKIT=0
    volumes:
      - .:/app
    depends_on:
      - redis
      - celerybeat

  celerybeat:
    build: .
    command: celery -A config beat -l DEBUG
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
