version: '3'

services:
  web:
    build: .
    container_name: flight-finder
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - HOST=0.0.0.0
      - DOCKER_BUILDKIT=0
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - celerybeat

  celeryworker:
    build: .
    command: celery -A config worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - rabbitmq

  celerybeat:
    build: .
    command: celery -A config  beat --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Port AMQP
      - "15672:15672"  # Port RabbitMQ Management


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
