# Generated by Django 5.0.2 on 2024-03-04 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightfinder', '0002_alter_flightprice_price_flightsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightsearch',
            name='flight_price',
        ),
    ]
