# Generated by Django 5.0.2 on 2024-03-04 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightfinder', '0003_remove_flightsearch_flight_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsearch',
            name='arrival_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_city_search', to='flightfinder.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightsearch',
            name='departure_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departure_city_search', to='flightfinder.city'),
            preserve_default=False,
        ),
    ]
