# Generated by Django 5.0.2 on 2024-03-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightfinder', '0007_sidebardestinations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SidebarDestinations',
            new_name='SidebarDestination',
        ),
    ]
