# Generated by Django 5.0.2 on 2024-08-11 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightfinder', '0009_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPlanSearchDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketPlanDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_ticket', to='flightfinder.city')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='flightfinder.city')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search', to='flightfinder.ticketplansearchdisplay')),
            ],
        ),
    ]
