# Generated by Django 5.0.2 on 2024-08-11 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightfinder', '0010_ticketplansearchdisplay_ticketplandisplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketplansearchdisplay',
            name='arrival_city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='arrival_city_display', to='flightfinder.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketplansearchdisplay',
            name='departure_city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='departure_city_display', to='flightfinder.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketplansearchdisplay',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
