# Generated by Django 5.0.2 on 2024-08-11 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightfinder', '0011_ticketplansearchdisplay_arrival_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketplandisplay',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketplandisplay',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketplandisplay',
            name='weekend_days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketplandisplay',
            name='return_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_ticket', to='flightfinder.flightprice'),
        ),
        migrations.AlterField(
            model_name='ticketplandisplay',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='flightfinder.flightprice'),
        ),
    ]
