# Generated by Django 5.0.2 on 2024-08-18 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightfinder', '0012_ticketplandisplay_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date_time', models.DateTimeField()),
                ('airline', models.CharField(max_length=24)),
                ('departure_airport', models.CharField(blank=True, max_length=24, null=True)),
                ('arrival_airport', models.CharField(blank=True, max_length=24, null=True)),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_specific_city', to='flightfinder.city')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_specific_flight', to='flightfinder.city')),
            ],
        ),
    ]
