# Generated by Django 5.0.2 on 2024-08-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightfinder', '0013_specificflight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificflight',
            old_name='flight_date_time',
            new_name='arrival_date_time',
        ),
        migrations.AddField(
            model_name='specificflight',
            name='departure_date_time',
            field=models.DateTimeField(default='2024-01-01 11:11'),
            preserve_default=False,
        ),
    ]
