# Generated by Django 5.0.2 on 2024-08-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightfinder', '0014_rename_flight_date_time_specificflight_arrival_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificflight',
            old_name='arrival_date_time',
            new_name='arrival_data_time',
        ),
        migrations.RenameField(
            model_name='specificflight',
            old_name='departure_date_time',
            new_name='departure_data_time',
        ),
    ]
