# Generated by Django 5.0.2 on 2024-08-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightfinder', '0017_city_genitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='city/images/'),
        ),
    ]
