# Generated by Django 5.0.2 on 2024-09-09 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightfinder', '0018_city_thumbnail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('flight_google_link', models.CharField(max_length=256)),
                ('flight_return_google_link', models.CharField(max_length=256)),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_city_flightconnect', to='flightfinder.city')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_city_flightconnect', to='flightfinder.city')),
            ],
        ),
    ]
