# Generated by Django 5.0.2 on 2024-09-20 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightfinder', '0019_flightconnect'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateField()),
                ('return_flight_date', models.DateField()),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_city_flight_collection', to='flightfinder.city')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_city_flight_collection', to='flightfinder.city')),
                ('flight_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_collection', to='flightfinder.flightcollection')),
            ],
        ),
    ]
