# Generated by Django 5.0.2 on 2024-04-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='published_date',
            field=models.DateField(null=True),
        ),
    ]
