# Generated by Django 5.0.2 on 2024-04-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramservice', '0002_instagrampost_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
