# Generated by Django 5.0.2 on 2024-05-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramservice', '0004_instagramstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramstory',
            name='is_story_generated',
            field=models.BooleanField(default=False),
        ),
    ]
