# Generated by Django 5.0.2 on 2024-05-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramservice', '0005_instagramstory_is_story_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPostFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField(null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_image_generated', models.BooleanField(default=False)),
            ],
        ),
    ]
