# Generated by Django 5.0.2 on 2024-05-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramservice', '0006_instagrampostfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramstory',
            name='description_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramstory',
            name='description_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramstory',
            name='description_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramstory',
            name='description_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramstory',
            name='description_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramstory',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagramstory',
            name='title_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instagramstory',
            name='title_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instagramstory',
            name='title_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instagramstory',
            name='title_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instagramstory',
            name='title_5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
