# Generated by Django 5.0.2 on 2024-05-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramservice', '0009_remove_instagramstory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampostfact',
            name='hashtags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
