# Generated by Django 5.0.2 on 2024-05-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramservice', '0010_instagrampostfact_hashtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('title_1', models.CharField(blank=True, max_length=50, null=True)),
                ('description_1', models.TextField(blank=True, null=True)),
                ('title_2', models.CharField(blank=True, max_length=50, null=True)),
                ('description_2', models.TextField(blank=True, null=True)),
                ('title_3', models.CharField(blank=True, max_length=50, null=True)),
                ('description_3', models.TextField(blank=True, null=True)),
                ('title_4', models.CharField(blank=True, max_length=50, null=True)),
                ('description_4', models.TextField(blank=True, null=True)),
                ('title_5', models.CharField(blank=True, max_length=50, null=True)),
                ('description_5', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
