# Generated by Django 5.0.2 on 2024-05-12 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramservice', '0011_fact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampostfact',
            name='category',
        ),
        migrations.RemoveField(
            model_name='instagrampostfact',
            name='description',
        ),
        migrations.RemoveField(
            model_name='instagrampostfact',
            name='description_1',
        ),
        migrations.RemoveField(
            model_name='instagrampostfact',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='instagrampostfact',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='instagrampostfact',
            name='description_4',
        ),
        migrations.RemoveField(
            model_name='instagrampostfact',
            name='description_5',
        ),
        migrations.RemoveField(
            model_name='instagrampostfact',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='instagrampostfact',
            name='title',
        ),
        migrations.RemoveField(
            model_name='instagrampostfact',
            name='title_1',
        ),
        migrations.RemoveField(
            model_name='instagrampostfact',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='instagrampostfact',
            name='title_3',
        ),
        migrations.RemoveField(
            model_name='instagrampostfact',
            name='title_4',
        ),
        migrations.RemoveField(
            model_name='instagrampostfact',
            name='title_5',
        ),
        migrations.AddField(
            model_name='instagrampostfact',
            name='fact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instagramservice.fact'),
        ),
    ]
