# Generated by Django 5.0.2 on 2024-05-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramservice', '0013_fact_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='img_id',
            field=models.IntegerField(default=1),
        ),
    ]
