# Generated by Django 5.0.2 on 2024-05-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramservice', '0014_fact_img_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampostfact',
            name='priority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
