# Generated by Django 5.0.2 on 2024-05-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramservice', '0015_instagrampostfact_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampostfact',
            name='priority',
        ),
        migrations.AddField(
            model_name='fact',
            name='priority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
