# Generated by Django 5.0.2 on 2024-06-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramservice', '0016_remove_instagrampostfact_priority_fact_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('is_following_me', models.BooleanField(default=False)),
                ('commented', models.BooleanField(default=False)),
                ('liked', models.BooleanField(default=False)),
                ('followed', models.BooleanField(default=False)),
                ('following_amount', models.IntegerField(default=0)),
                ('followers_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
