# Generated by Django 5.0.2 on 2024-08-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramservice', '0018_alter_instagrampost_arrival_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='instagrampost/images/'),
        ),
    ]
