# Generated by Django 5.0.2 on 2024-08-31 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramservice', '0019_instagrampost_thumbnail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='thumbnail_image',
        ),
    ]
