# Generated by Django 5.0.2 on 2024-09-22 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightfinder', '0020_flightcollection_flightcollectionitem'),
        ('instagramservice', '0020_remove_instagrampost_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramstory',
            name='flight_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flightfinder.flightcollection'),
        ),
    ]
